Fixed two typos and rewrote some text in About us
expertanalytics/xal pull request #103
Opened 2020-10-19 12:31 UTC by kememil

2020-10-19 12:40 UTC, skavhaug requested changes

2020-10-19 12:40 UTC, skavhaug commented on content/about/_index.md
> +combined with solid backgrounds in the natural sciences, which translates into an
Backgrounds eller background? Uvant å se det ordet i flertallsform

2020-10-19 12:40 UTC, skavhaug commented on content/about/_index.md
> +Expert Analytics is a data-science consultancy based in Oslo, Norway. We offer
Vi er ikke utelukkende et data-science konsulentbyrå, så denne må fikses.

2020-10-19 12:52 UTC, kememil commented on content/about/_index.md
> +combined with solid backgrounds in the natural sciences, which translates into an
Enig :) Bruker "a solid background" i stedet. Og så skal det vel være an apostrof etter "years"

2020-10-19 12:53 UTC, kememil commented on content/about/_index.md
> +Expert Analytics is a data-science consultancy based in Oslo, Norway. We offer
ok, men software blir for vagt igjen....

2020-10-19 12:59 UTC, skavhaug commented on content/about/_index.md
> +combined with solid backgrounds in the natural sciences, which translates into an
Nope, ikke apostrof etter years, for det er ikke årenes vi mener?

2020-10-19 13:00 UTC, skavhaug commented on content/about/_index.md
> +Expert Analytics is a data-science consultancy based in Oslo, Norway. We offer
Tja, `analytics` we vel kanskje ikke riktig heller...

2020-10-20 08:03 UTC, eigilhs commented on content/about/_index.md
> +high-quality software solutions for industrial applicaitons to both domestic and
```suggestion
Expert Analytics is a high tech software consultancy based in Oslo, Norway. We offer
high-quality software solutions for industrial applications to both domestic and
```
Og det blir kanskje litt ekko med "high tech" og "high-quality" like etter hverandre?

2020-10-20 19:45 UTC, kememil commented on content/about/_index.md
> +high-quality software solutions for industrial applicaitons to both domestic and
Takk for finlesing :) Og eing i kommentaren om ekko!

2020-10-20 19:47 UTC, kememil commented on content/about/_index.md
> +high-quality software solutions for industrial applicaitons to both domestic and
Hva med å bytte ut "We offer high-quality software" med "We develop production ready software"?

2020-10-21 08:59 UTC, eigilhs commented on content/about/_index.md
> +high-quality software solutions for industrial applicaitons to both domestic and
Jeg tenker litt at «production ready» er minstemål for hva man kan levere. Hva med å bare stryke «high»?

> Expert Analytics is a high tech software consultancy based in Oslo, Norway. We offer quality software solutions […]

2020-10-21 10:40 UTC, skavhaug approved these changes

2020-10-21 11:26 UTC, merged